### ISSUE TITLE
API Calls and Helper Function

### ISSUE THREAD

**Issue by nicolerue** [Jnguyen615/Stretch-tech#33]

**Comment by loganpaulmatheny** [comment]
Tasks: 

- [ ] ID all components that go into connecting the API
- [ ] Take a look at API 
- [ ] Create helper function to clean data 
- [ ] Create API call - utilize promise.all to wait for all of the requests to complete
- [ ] Connect state to API calls 

Acceptance Criteria: 

- [ ] All API calls are correctly stubbed
- [ ] Helper function clarifies data that we need
